project_name: health-ftp
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: main
    main: .
    binary: health-ftp
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
  - id: health-ftp-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
nfpms:
  -
    id: health-ftp-nfpms
    package_name: health-ftp
    builds:
      - health-ftp-linux
    homepage: https://github.com/transnano/http-status-for-ftp
    maintainer: Transnano <transnano.jp@gmail.com>
    description: health-ftp is http health checker for ftp server.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1
