project_name: http-status-for-ftp
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: health-ftp
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version=$(git describe --tags --abbrev=0)
      - -X github.com/prometheus/common/version.BuildDate=$(date +%FT%T%z)
      - -X github.com/prometheus/common/version.Branch=$(git branch -a | grep -E '^\*' | cut -b 3-)
      - -X github.com/prometheus/common/version.Revision=$(git rev-parse --short HEAD)
      - -X github.com/prometheus/common/version.BuildUser=$(whoami)
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
nfpms:
  -
    id: health-ftp-nfpms
    package_name: health-ftp
    homepage: https://github.com/transnano/http-status-for-ftp
    maintainer: Transnano <transnano.jp@gmail.com>
    description: health-ftp is http health checker for ftp server.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1
